In [2]:
# Importar a classe 
from metodo_hungaro import AlgoritmoHungaro
import numpy as np

# Criar matriz de custos de exemplo
matriz_custos = np.array([
    [13, 22, 19, 21, 16, 20],
    [18, 17, 24, 18, 22, 27],
    [20, 22, 23, 24, 17, 31],
    [14, 19, 13, 30, 23, 22],
    [21, 14, 17, 25, 15, 23],
    [17, 23, 18, 20, 16, 24]
])

# Criar instância do solver
solver = AlgoritmoHungaro(matriz_custos)

# Resolver para minimização
custo_total, matriz_resposta = solver.resolver(maximizar=False)

# Imprimir resultados formatados
solver.imprimir_solucao()



Custo total da atribuição: 99.00

Atribuições:
Agente 0 -> Tarefa 0 (custo: 13.00)
Agente 1 -> Tarefa 3 (custo: 18.00)
Agente 2 -> Tarefa 4 (custo: 17.00)
Agente 3 -> Tarefa 2 (custo: 13.00)
Agente 4 -> Tarefa 1 (custo: 14.00)
Agente 5 -> Tarefa 5 (custo: 24.00)

Matriz de atribuição (mostra apenas elementos escolhidos):
[[13.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 18.  0.  0.]
 [ 0.  0.  0.  0. 17.  0.]
 [ 0.  0. 13.  0.  0.  0.]
 [ 0. 14.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 24.]]
